
	public enum Command
	{
		EXIT_APPLICATION, ADD_CLIENT, REMOVE_CLIENT, LIST_ALL_CLIENTS, ADD_CUSTOMER, REMOVE_CUSTOMER, 
		LIST_ALL_CUSTOMERS, ADD_CREDIT_CARD, REMOVE_CREDIT_CARD, ADD_SHOW, LIST_ALL_SHOWS, STORE_DATA, 
		RETRIEVE_DATA, HELP, BAD_COMMAND
	}